// import 'semantic-ui-css/semantic.min.css';
// import 'semantic-ui-css/components/Site.css';
// import 'semantic-ui-css/components/Reset.css';
// import 'semantic-ui-css/components/Container.css';
// import 'semantic-ui-css/components/Menu.css';
// import 'semantic-ui-css/components/Header.css';
// import 'semantic-ui-css/components/Divider.css';
// import 'semantic-ui-css/components/Grid.css';
// import 'semantic-ui-css/components/Segment.css';
// import 'semantic-ui-css/components/List.css';
// import 'semantic-ui-css/components/Button.css';
// import 'semantic-ui-css/components/Statistic.css';
// import 'semantic-ui-css/components/Image.css';
// import 'semantic-ui-css/components/Icon.css';
// import 'semantic-ui-css/components/Input.css';
// import 'semantic-ui-css/components/Checkbox.css';
// import 'semantic-ui-css/components/Transition.css';
// import 'semantic-ui-css/components/Dropdown.css';
// import 'semantic-ui-css/components/Breadcrumb.css';
// import 'semantic-ui-css/components/Label.css';
// import 'semantic-ui-css/components/Form.css';
// import 'semantic-ui-css/components/Message.css';
// import 'semantic-ui-css/components/Loader.css';
// import 'semantic-ui-css/components/Modal.css';
// import 'semantic-ui-css/components/Dimmer.css';
// import 'semantic-ui-css/components/Transition.css';
// import 'semantic-ui-css/components/Popup.css';

import './style/main';
import App from './app';

export default App;
